pull_request_rules:
  - name: Automatic merge ⬇️ renovate PR
    conditions:
      - "#approved-reviews-by>=1"
      - "author=renovate[bot]"
      - "check-success=test"
      - "check-success=build"
      - "check-success=lint"
    actions:
      merge:
        method: merge
