name: Release

on:
  push:
    branches:
      - master

jobs:
  deploy-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 1

      - name: Use Node.js 14.x
        uses: actions/setup-node@v2.1.4
        with:
          node-version: 14

      - name: Cache node modules
        id: cache
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: yarn --frozen-lockfile --silent
        env:
          HUSKY_SKIP_INSTALL: true

      - name: Build
        run: |
          yarn build
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Test
        run: |
          yarn test:cov
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1.3.2
        with:
          token: ${{secrets.CODECOV_TOKEN}}
          file: ./coverage/clover.xml
          name: codecov-umbrella

      - name: Release
        run: |
          yarn release
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
